# Generated by Django 5.2 on 2025-04-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(default='Departmenf of Trade and Industry Region IV-A', max_length=200)),
                ('fund_cluster', models.CharField(default='01-Regular Agency Fund', max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('collecting_officer', models.CharField(default='Cash/Treasury Unit', max_length=200)),
                ('payor', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('fee_type_1', models.CharField(max_length=200)),
                ('fee_type_1_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type_2', models.CharField(blank=True, max_length=200, null=True)),
                ('fee_type_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_type_3', models.CharField(blank=True, max_length=200, null=True)),
                ('fee_type_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surcharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_words', models.CharField(max_length=500)),
                ('bill_no', models.CharField(max_length=200)),
                ('bill_date', models.DateField()),
                ('status', models.CharField(default='NEW', max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acting_accountant', models.CharField(max_length=200)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('last_update_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Of Payment Items',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
