# Generated by Django 5.2 on 2025-04-15 23:43

import order_payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentitem',
            name='extra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderpaymentitem',
            name='serial_number',
            field=models.CharField(default=order_payment.models.generate_serial, max_length=200),
        ),
    ]
